### ISSUE TITLE
Extract HVIF Data from the HPKG on Import

### ISSUE THREAD

**Issue by aplgithub** [haiku/haikudepotserver#110]
When a package is imported from HPGR, the main binary will typically have an attribute (see `B_HPKG_ATTRIBUTE_ID_FILE_ATTRIBUTE` [here](https://dev.haiku-os.org/wiki/PackageManagement/FileFormat#AttributeIDs) with value "BEOS:ICON".  This can be extracted to obtain the HVIF data to load against the package.  This would eliminate the need for a person to manually copy those HVIF data files into the package in the web interface.

**Comment by diversys** [comment]
How would it choose which one to use if there are several binaries with "BEOS:ICON" inside?

**Comment by aplgithub** [comment]
In this case, it would be ambiguous and the package would be left with no icon.  This situation would require manual intervention, but for many cases, being able to pickup the HVIF data automatically would save some time.
