### ISSUE TITLE
Investigate Use of ".po" Files and Infrastructure for Web App Localization

### ISSUE THREAD

**Issue by aplgithub** [haiku/haikudepotserver#119]
(c.f. helix84 on mailing list) It has been suggested that making use of a richer localization framework would allow for the more convenient use of ".po" files for localization.  It might also handle pluralization and argument swapping that would be nicer.  AngularJS has a [localization](https://docs.angularjs.org/guide/i18n) framework, but given the disruption, it may be better to wait for significant changes to warrant making such a disruptive enhancement.  Another factor is that the Java and SPA environments need to be able to share localization so a consistent infrastructure would need to exist across both environments.

**Comment by helix84** [comment]
My comment at https://github.com/aplgithub/haikudepotserver/issues/118#issuecomment-272137768 applies here, too.

**Comment by aplgithub** [comment]
Dup of #119
