### ISSUE TITLE
Set x86_64 architecture by default

### ISSUE THREAD

**Issue by diversys** [haiku/haikudepotserver#162]
Reasons for that:
Stats show that x86_64 Haiku is what used the most nowadays (I don't remember where I saw download stats tho)
Resouces are only copied from x86_64 to x86_gcc2 packages and not the other way around.

**Comment by aplgithub** [comment]
Hello; the default to "x86_64" from "x86_gcc2" will go out in the next release.  With respect to the statement;

>  Resouces are only copied from x86_64 to x86_gcc2 packages and not the other way around.

Can you please open a new ticket and explain in more detail what is the actual and desired behaviour?
