### ISSUE TITLE
Resouces do not get carried from x86 to x86_64 packages

### ISSUE THREAD

**Issue by diversys** [haiku/haikudepotserver#164]
Resouces are only copied from x86_64 to x86_gcc2 packages and not the other way around.

See more here https://github.com/haiku/haikudepotserver/issues/114#issuecomment-355830613

**Comment by aplgithub** [comment]
Rather than copying data around which is already quite messy and would get even more messy bi-directionally, I will re-factor the data model so that the packages are able to share the data.  This will be a better long-term strategy.  This will be a quite tricky as it will touch a number of areas of the system.  There will soon be a release of HDS ready and I will wait until that has settled in production before looking into this one.

**Comment by aplgithub** [comment]
I have the following set of packages as an example;

* libpcre0
* libpcre0_source
* libpcre0_x86
* libpcre0_x86_source
* libpcre2
* libpcre2_devel
* libpcre2_source
* libpcre2_x86
* libpcre2_x86_devel
* libpcre2_x86_source
* libpcre
* libpcre_debuginfo
* libpcre_devel
* libpcre_source
* libpcre_x86
* libpcre_x86_debuginfo
* libpcre_x86_devel
* libpcre_x86_source

Can you verify which of these should share their;

* icons
* screenshots
* localizations
* package categorization

**Comment by diversys** [comment]
Yes, all these and maybe prominence too?

**Comment by aplgithub** [comment]
I don't think prominence should be shared like this.  It would be a bit strange to get "<base-package-name>" on the front-page and have to also have the "_devel" package there as well.

Can you please comment on the arrangement (algorithm) by which packages know to share data with each other.  At present the following package name pattern is used;

* <base-package-name>
* <base-package-name>_devel
* <base-package-name>_x86
* <base-package-name>_x86_devel

Should this pattern also be extended to...

* <base-package-name>_source
* <base-package-name>_x86_source
* <base-package-name>_debuginfo
* <base-package-name>_x86_debuginfo

...?

Are you using any other suffix patterns that are involved?  @waddlesplash -- you may have some insight here?

**Comment by diversys** [comment]
I meant prominence should probably be carried from x86 to x86_64 too. BTW, do we really need to see debuginfo packages in HDS? Maybe hide them by default with an option to show them if really needed.
I mean debuginfo is something which needed in extremely rare cases.

**Comment by aplgithub** [comment]
@diversys ; can you please open two new tickets explaining;

* That prominence should be shared and explain the algorithm to ascertain which packages should share the same prominence.
* Delete "_debuginfo" packages and ignore them on import.

**Comment by aplgithub** [comment]
This should be resolved in the 1.0.109 / 1.0.110 deployment.
