### ISSUE TITLE
unable to import the fatelk.com repo

### ISSUE THREAD

**Issue by bbjimmy** [haiku/haikudepotserver#177]
https://depot.haiku-os.org/repository/fatelk/import

Haiku Depot Server

Oh darn! The requested resource was not found.

**Comment by aplgithub** [comment]
Hello @bbjimmy ; use the URL form...

```
https://depot.haiku-os.org/__repository/fatelk/import
```

Note the "__".  Note that the system now supports a password for each repository.  It would be good if you could get in touch with @kallisti5 and setup a password for the repository API in order to keep the system secure.

**Comment by bbjimmy** [comment]
Thanks, the import worked. I already have a username and password for the HDS, do I need another for  the fatelk repo?

**Comment by aplgithub** [comment]
Yes the password will be a different one just for the repository.
