### ISSUE TITLE
"Featured packages" tab empty for Friaulian locale

### ISSUE THREAD

**Issue by humdingerb** [haiku/haikudepotserver#187]
If you set the language to Friaulian in the Locale prefs, the "Featured packages" tab remains empty after only a short activity of HaikuDepot's progress bar. Other languages are fine.

Terminal output mentions: "set preferred language [fu]"

Is it possible that this should be "fur"? At least that's the more usual language code...

I assume this is a HDS issue instead of a HaikuDepot app issue. If it isn't please close and I'll move the ticket to Haiku's Trac.

**Comment by humdingerb** [comment]
Screenshots and altered English application names (e.g. "artpaint" -> "ArtPaint") are missing as well. Icons and ratings are OK.

**Comment by aplgithub** [comment]
Hi; It seems that...

```
SELECT * FROM haikudepot.natural_language WHERE code LIKE 'f%';
```

...the Friaulian language is not in the list of natural languages in HDS...

```
 code |  id  |      name       | is_popular |  create_timestamp   |  modify_timestamp   
------+------+-----------------+------------+---------------------+---------------------
 fr   | 9402 | French          | t          | 2010-01-01 00:00:00 | 2010-01-01 00:00:00
 fo   | 9448 | Faroese         | f          | 2010-01-01 00:00:00 | 2010-01-01 00:00:00
 fj   | 9449 | Fijian          | f          | 2010-01-01 00:00:00 | 2010-01-01 00:00:00
 fi   | 9450 | Finnish         | f          | 2010-01-01 00:00:00 | 2010-01-01 00:00:00
 fy   | 9451 | Western Frisian | f          | 2010-01-01 00:00:00 | 2010-01-01 00:00:00
 ff   | 9452 | Fulah           | f          | 2010-01-01 00:00:00 | 2010-01-01 00:00:00
 fa   | 9526 | Persian         | f          | 2010-01-01 00:00:00 | 2010-01-01 00:00:00
```

Two problems here;

1. The system should be returning defaulting to English and returning something
2. The Friaulian language should be added

How urgent is this?

**Comment by humdingerb** [comment]
Not particularly. I just did many screenshots for the user guide for half a dozen languages and came upon this issue for Friaulian. Whenever you find the time... :)

**Comment by aplgithub** [comment]
I don't think that the Friaulian language has a two letter [ISO code](http://loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt) but Haiku-OS seems to be using `fu` from the trace above.  Did you add that yourself or is that standard as I can't see it in the source code and I think Haiku, as with HDS, uses the two letter ISO codes.

**Comment by humdingerb** [comment]
I didn't add anything. "fu" is apparently what the BLocaleRoster supplies, see https://git.haiku-os.org/haiku/tree/src/apps/haikudepot/model/LanguageModel.cpp#n139

"locale -l", after setting Friaulian in the Locale prefs, returns "fur_IT" though...

**Comment by aplgithub** [comment]
I will hold back from adding the language to HDS until there's a clear ISO 2 letter code for the language.  However recent changes should mean that at least the English data should come through in this case.  This will go out in the next deployment.
