### ISSUE TITLE
Search doesn't find some packages

### ISSUE THREAD

**Issue by diversys** [haiku/haikudepotserver#211]
Searching for "smb" should find https://depot.haiku-os.org/kio_extras package as there in smb in its description.

**Comment by aplgithub** [comment]
It searches in the title and the summary, but not the description.  It seems excessive to search also in the description?

**Comment by diversys** [comment]
HaikuDepot searches in both places so it kinda make sense to replicate this behaviour here too.

**Comment by aplgithub** [comment]
I will take this question to the mailing list to gather some opinions.  I think that querying also the descriptions will lead to a situation where there are too many false negatives because the test is too long and it would be too easy to hit a keyword.

**Comment by aplgithub** [comment]
Sounds like from a brief show of hands in the mailing list that searching in the descriptions as suggested makes sense.
