### ISSUE TITLE
RSS Feeds: add setting for locale

### ISSUE THREAD

**Issue by humdingerb** [haiku/haikudepotserver#214]
If possible, it'd be nice if you could choose a locale for the RSS feed and get the descriptions localized.

**Comment by aplgithub** [comment]
Hi Humdinger; are you able to check this](https://depot.haiku-os.org/__feed/pkg.atom?natlangcode=de&limit=25&types=CREATEDPKGVERSION,CREATEDUSERRATING) again as it seems to work for me.  If I try this URL then I get German descriptions such as;

```
  <entry>
    <title>MidiSynth - 1.8.0-1 - Neue Version</title>
    <link rel="alternate" href="https://depot.haiku-os.org/#!/pkg/midisynth/haikuports/1/8/0/-/1/x86_64" />
    <author>
      <name />
    </author>
    <id>urn:hdsfeedentry:ded4c32c6a5048b6b22d0413153878c2ae2623bc</id>
    <updated>2021-02-25T07:39:08Z</updated>
    <published>2021-02-24T20:18:19Z</published>
    <summary type="text">Ein einfaches Software MIDI Keyboard</summary>
    <dc:date>2021-02-24T20:18:19Z</dc:date>
  </entry>
```
If I use [this](https://depot.haiku-os.org/__feed/pkg.atom?natlangcode=en&limit=25&types=CREATEDPKGVERSION,CREATEDUSERRATING) URL then I get such an entry;
```
  <entry>
    <title>MidiSynth - 1.8.0-1 - new version</title>
    <link rel="alternate" href="https://depot.haiku-os.org/#!/pkg/midisynth/haikuports/1/8/0/-/1/x86_64" />
    <author>
      <name />
    </author>
    <id>urn:hdsfeedentry:ded4c32c6a5048b6b22d0413153878c2ae2623bc</id>
    <updated>2021-02-25T07:39:08Z</updated>
    <published>2021-02-24T20:18:19Z</published>
    <summary type="text">A simple software MIDI keyboard</summary>
    <dc:date>2021-02-24T20:18:19Z</dc:date>
  </entry>
```

**Comment by humdingerb** [comment]
Hi Andrew Lindesay!

On Thu, 25 Feb 2021 01:08:02 -0800 Andrew Lindesay wrote:
> Hi Humdinger; are you able to check this](https://depot.haiku-os.org/__feed/pkg.atom?natlangcode=de&limit=25&types=CREATEDPKGVERSION,
> > CREATEDUSERRATING) again as it seems to 
> work for me.  If I try this URL then I get German descriptions such as;

Yep, shows the German version for me as well. It's good! :)

Regards,
Humdinger

--
Help translating 3rd party Haiku applications
Go to Polyglot at https://i18n.kacperkasper.pl
