### ISSUE TITLE
Can't download generated reports

### ISSUE THREAD

**Issue by humdingerb** [haiku/haikudepotserver#217]
I created a report "Package Prominence and User Ratings Spreadsheet", but am unable to download the generated file (at least with Otter and Web+). Web+'s script console says: "Refused to display 'https://....the loooooong URL...' in a frame bcause it set 'X-Frame-Options' to 'DENY'.

Right-clicking the URL doesn't present a download option either.

The same for other reports.

**Comment by aplgithub** [comment]
Thanks for letting me know Humdinger; I will try to take a look into this in the next couple of days.
