### ISSUE TITLE
alex4 allegator 64bit

### ISSUE THREAD

**Issue by lorglas** [haiku/haikudepotserver#218]
i want to play the game, the intro works, but if i want to play the first level, i didn't see the allegator and i get no response from the keyboard or mouse.

**Comment by aplgithub** [comment]
Hi @lorglas ; this project is the HaikuDepotServer one and not the HaikuPorts; I presume you had meant to open it under HaikuPorts?

**Comment by lorglas** [comment]
Sorry, it was to late yesterday
