### ISSUE TITLE
Possibly lost fallback-translations

### ISSUE THREAD

**Issue by humdingerb** [haiku/haikudepotserver#221]
I get the feeling, that sometimes fallback-translation are lost...
I cannot be 100% sure, but there are some quite old packages, like Critical Mass, that have been a long time in HDS and are featured packages. I've tried to keep up with German translations at least for enduser applications, and esp. for packages in the "Featured" tab.
So I'm pretty sure I've translated "Critical Mass" already, but currently there's no German translation (anymore). Another example is "Colors!", though I've (re-)translated that one now.
"Fontboy" is another candidate, thats missing its German translation.

As I said, I cannot be 100% sure, but I think I do have dejá-vus...

**Comment by diversys** [comment]
Could be related to #176.

**Comment by aplgithub** [comment]
Hi; look I'm sorry, the migration a year ago might have gone wrong and has caused this data-loss.  I am not sure what the best process is here as it could take a very long time to retrospectively "fix".

**Comment by humdingerb** [comment]
No worries. If it was a migration accident a year ago, there's probably nothing that could be reasonably done now. I just wanted to mention it, in case there's an actual systemic problem.
Feel free to close this issue.
