### ISSUE TITLE
Package size is missing for some packages

### ISSUE THREAD

**Issue by diversys** [haiku/haikudepotserver#224]
https://depot.haiku-os.org/#!/?srchexpr=gpg

libassuan_debuginfo
libassuan_devel

**Comment by aplgithub** [comment]
To resolve this, somebody with root access on the HDS system will need to run the "Populate payload lengths for package versions that are missing them" operation which is accessible from the "Root operations" on the top-right menu.

**Comment by aplgithub** [comment]
I have requested this on the Haiku sys-admin mailing list.

**Comment by nielx** [comment]
I tried running the action but I get an error page. This is the log:

> 06:08:41.044 [http-nio-8080-exec-1956] INFO  o.h.h.support.web.ErrorServlet - not found [/__multipage/pkg/libxcm_devel/haikuports/haikuports_x86_64/0/5/4/-/2/x86_64]
> 06:08:41.402 [http-nio-8080-exec-1980] WARN  o.s.web.servlet.PageNotFound - No mapping for POST /__api/v2/pkg/queue-pkg-version-payload-length-population-job
> 06:08:41.404 [http-nio-8080-exec-1980] INFO  o.h.h.support.web.ErrorServlet - not found [/__api/v2/pkg/queue-pkg-version-payload-length-population-job]
> 06:08:41.444 [http-nio-8080-exec-1989] ERROR org.haiku.haikudepotserver.js - rpc error; code:-32100, msg:transport-failure
> 06:08:41.446 [http-nio-8080-exec-1995] ERROR o.h.h.support.web.ErrorServlet - failed request to [null] (0); null

**Comment by aplgithub** [comment]
Thanks @nielx ; I am away a few days now, but will check on this when I get back to see what the problem is.

**Comment by andponlin** [comment]
@nielx ; once 1.0.151 is deployed can you please try this again for me?

**Comment by nielx** [comment]
I have updated the deployment to HDS 1.0.151 and re-run the job, and i now see sizes for these packages.
