### ISSUE TITLE
Link to latest version of a package for 32 bit packages

### ISSUE THREAD

**Issue by phw** [haiku/haikudepotserver#238]
I used to link to the latest version of a package with a URL in the form of `https://depot.haiku-os.org/{package_name}`, e.g. the following link leads to the latest version of the package "picard":

https://depot.haiku-os.org/picard

This works well and redirects to the latest version of this package. But I don't seem to be able to link to the 32 bit version of the same package anymore. This used to work:

https://depot.haiku-os.org/picard_x86

But not anymore, it now just gives a 404 response with the text "unable to find an entity for; picard_x86". But there is https://depot.haiku-os.org/#!/pkg/picard_x86/haikuports/haikuports_x86_gcc2/2/8/2/-/1/x86_gcc2 , and the shown package name is "picard_x86".

Is this a bug or wrong usage of the URL structure?

**Comment by aplgithub** [comment]
Hi @phw ; Thanks for pointing this out.  It is because it is only looking for the default architecture `x86_64`.  At some point in the past the default architecture changed from `x86_gcc2` to `x86_64` so this is probably the cause.  I am currently working through some larger changes, but will try to loop back to this soon.

**Comment by phw** [comment]
Ok, interesting. But at some point in the past both links worked and ended up on the 64 bit or 32 bit package page.

I don't know when this changed, though.

**Comment by phw** [comment]
I saw the new version of haikudepotserver has been deployed, and the link is now working again. Thanks a lot for this quick fix!

**Comment by aplgithub** [comment]
Hi @phw ; glad it's working properly now!
