### ISSUE TITLE
HDS website: tiny text for summaries in main list

### ISSUE THREAD

**Issue by humdingerb** [haiku/haikudepotserver#243]
Has something changed on the main list view? It appears the summary's text got smaller. Or did my eyes get worse...? :)

![smalltext](https://user-images.githubusercontent.com/6107158/200111711-460b44e5-5f16-475e-9f32-7e655e981370.png)

**Comment by aplgithub** [comment]
I don't think I have changed anything in the style-sheets for a very long time?

**Comment by humdingerb** [comment]
Comparing a current Web+ rendering, the text now appears a bit larger:

![screenshot1](https://github.com/haiku/haikudepotserver/assets/6107158/7537da9d-69a1-459d-94d8-596bdb8fdd59)

Maybe some temporary webkit issue? Never mind, it's back to a size my old eyes are able to resolve. Barely. :)
Close ticket? After all, a little zoom in is just an ALT + away...

**Comment by aplgithub** [comment]
It looks like it is 10px height in the CSS (see styling for `small`) this can be seen in the `main.css` file. Do you want to open the CSS editor in a mainstream browser and try change that to 11px or 12px and see if that is any better?

**Comment by humdingerb** [comment]
Did that now, and I think using 12px would be nice. Much easier on the eyes and doesn't make the lines that much longer. Those are the summaries, which aren't that long anyway.
Thanks!
