### ISSUE TITLE
Typo in string

### ISSUE THREAD

**Issue by jt15s** [haiku/haikudepotserver#249]
Just noticed a small typo in one of the strings whilst localising HDS via Polyglot. 

The string `account.initiatePasswordReset.done.description`
 reads:
If your request is successful, you will receive an email with **furtherinstructions** relating to resetting the password for this

This should be changed to:
If your request is successful, you will receive an email with **further instructions** relating to resetting the password for this

Thanks!

**Comment by andponlin** [comment]
Thanks for pointing this out!

**Comment by jt15s** [comment]
No worries! :)
