### ISSUE TITLE
Pull translations from Polyglot

### ISSUE THREAD

**Issue by bitigchi** [haiku/haikudepotserver#255]

**Comment by andponlin** [comment]
Hi; I expect you mean to pull the translations from Polygot? This cannot be done at this moment because I am waiting to be able to unify the languages between HDS and Polygot. I am working on this at the current time so hopefully not too far off. Leave this ticket open as a reminder.

**Comment by bitigchi** [comment]
Sorry, yes, Polyglot. Brain error happened.

**Comment by andponlin** [comment]
This will be deployed in the next release.
