### ISSUE TITLE
A package missing its icon

### ISSUE THREAD

**Issue by humdingerb** [haiku/haikudepotserver#260]
The package of [Pogger](https://depot.haiku-os.org/#!/pkg/pogger/haikuports/haikuports_x86_64/0/0/1/git/1/x86_64) doesn't have its icon, though it is a regular HVIF icon. Maybe a good candidate to inspect what's going on there,

**Comment by andponlin** [comment]
It looks like there are two Applications supplied by this package and so HDS is unable to choose which is the right one to use;

```
package:name : STRING : pogger
...
toc:
-------------------
dir:entry : STRING : apps
...
  dir:entry : STRING : Pogger
...
    dir:entry : STRING : Pogger
...
      file:attribute : STRING : BEOS:ICON
        file:attribute:type : INT : 1447641934
        data : RAW : 723 bytes {off:519985, len:723}
    dir:entry : STRING : PoggerShadow
 ...
      file:attribute : STRING : BEOS:ICON
        file:attribute:type : INT : 1447641934
        data : RAW : 723 bytes {off:922981, len:723}
...
```

It looks like the icon is _probably_ the same in both cases, but this is not always going to be the case. I am guessing that in this situation, it would be better that the package had an icon applied manually?

**Comment by humdingerb** [comment]
> I am guessing that in this situation, it would be better that the package had an icon applied manually

Yes, I think that makes sense. But it's good that we now know the reason when a package has the default icon. Thanks for having a look.

**Comment by andponlin** [comment]
:+1: - no problem.

**Comment by andponlin** [comment]
> But it's good that we now know the reason when a package has the default icon.

Just thinking about this a bit more. Do you think it would actually be better to just choose any of the icons and apply it? Then this way, even if it chooses the wrong one, it could be corrected by an admin?

**Comment by humdingerb** [comment]
Not a good idea, I think. If I see an app having a non-default icon in HDS, I assume it's the correct (only) icon of the app/package. I have to, because otherwise I'd have to check every package to make sure it's the correct one.
The luxery solution would of course be a selection window that shows all icons and their application name to choose one. But that's too much work for little gain.
It's quite exceptional to happen upon a missing-icon-package.
